services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\AdminUi\UI\Module\ContentTree\NodeFactory:
        arguments:
            $contentService: '@ezpublish.api.service.content'
            $translationHelper: '@ezpublish.translation_helper'
            $configResolver: '@ezpublish.config.resolver'
            $maxLocationIdsInSingleAggregation: '%ibexa.admin_ui.content_tree.node_factory.max_location_ids_in_single_aggregation%'

    Ibexa\AdminUi\UI\Config\Provider\Module\ContentTree:
        tags:
            - { name: ezplatform.admin_ui.config_provider, key: 'contentTree' }
