services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\AdminUi\UI\Module\FieldTypeToolbar\FieldTypeToolbarFactory:
        arguments:
            - '@Ibexa\Core\FieldType\FieldTypeRegistry'
            - '@translator'
