services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\AdminUi\UI\Module\Subitems\ValueObjectVisitor\SubitemsRow:
        parent: ezpublish_rest.output.value_object_visitor.base
        autowire: true
        autoconfigure: false
        public: true
        tags:
            - { name: ibexa.rest.output.value_object.visitor, type: Ibexa\AdminUi\UI\Module\Subitems\Values\SubitemsRow }

    Ibexa\AdminUi\UI\Module\Subitems\ValueObjectVisitor\SubitemsList:
        parent: ezpublish_rest.output.value_object_visitor.base
        autowire: true
        autoconfigure: false
        public: true
        tags:
            - { name: ibexa.rest.output.value_object.visitor, type: Ibexa\AdminUi\UI\Module\Subitems\Values\SubitemsList }

    Ibexa\AdminUi\UI\Module\Subitems\ContentViewParameterSupplier:
        $outputVisitor: '@ezpublish_rest.output.visitor.json'
        $outputGenerator: '@ezpublish_rest.output.generator.json'
        $contentTypeInfoListValueObjectVisitor: '@ezpublish_rest.output.value_object_visitor.ContentTypeInfoList'
