services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\AdminUi\Config\AdminUiForms\ContentTypeFieldTypesResolver: ~

    Ibexa\AdminUi\Config\AdminUiForms\ContentTypeFieldTypesResolverInterface:
        '@Ibexa\AdminUi\Config\AdminUiForms\ContentTypeFieldTypesResolver'
