parameters:
    ibexa.content_forms.form_processor.content_type.options.redirect_route_after_publish: ~
    ibexa.content_forms.form_processor.content_type.options:
        redirectRouteAfterPublish: '%ibexa.content_forms.form_processor.content_type.options.redirect_route_after_publish%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Form\Processor\:
        resource: "../../../../lib/Form/Processor/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\Form\Processor\Content\AutosaveProcessor: ~

    Ibexa\AdminUi\Form\Processor\Content\ContentOnTheFlyProcessor:
        arguments:
            $innerContentFormProcessor: '@Ibexa\ContentForms\Form\Processor\ContentFormProcessor'

    Ibexa\AdminUi\Form\Processor\Content\UrlRedirectProcessor:
        public: true
        decorates: Ibexa\ContentForms\Form\Processor\SystemUrlRedirectProcessor
        arguments:
            $siteaccessGroups: '%ibexa.site_access.groups%'
            $systemUrlRedirectProcessor: '@Ibexa\AdminUi\Form\Processor\Content\UrlRedirectProcessor.inner'

    Ibexa\AdminUi\Form\Processor\ContentEditNotificationFormProcessor:
        public: true
        arguments:
            $siteAccessGroups: '%ibexa.site_access.groups%'

    Ibexa\AdminUi\Form\Processor\ContentType\ContentTypeDiscardChangesFormProcessor: ~

    Ibexa\AdminUi\Form\Processor\ContentType\ContentTypeFormProcessor:
        arguments:
            - '@ibexa.api.service.content_type'
            - "@router"
            - '%ibexa.content_forms.form_processor.content_type.options%'
        calls:
            - [ setGroupsList, [ '@Ibexa\Core\Helper\FieldsGroups\FieldsGroupsList' ] ]

    Ibexa\AdminUi\Form\Processor\PreviewFormProcessor: ~

    Ibexa\AdminUi\Form\Processor\TranslationFormProcessor: ~

    Ibexa\AdminUi\Form\Processor\User\UserOnTheFlyProcessor:
        arguments:
            $innerUserUpdateFormProcessor: '@Ibexa\ContentForms\Form\Processor\User\UserUpdateFormProcessor'
