services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\QueryType\LocationPathQueryType: ~

    Ibexa\AdminUi\QueryType\ContentSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\ContentLocationSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\MediaSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\MediaLocationSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\TrashSearchQueryType: ~

    Ibexa\AdminUi\QueryType\UserQueryType: ~
