services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Strategy\NotificationTwigStrategy: ~

    Ibexa\AdminUi\Strategy\ContentTypeThumbnailStrategy:
        tags:
            - { name: ibexa.repository.thumbnail.strategy.content, priority: -100 }

    Ibexa\AdminUi\Strategy\FocusMode\ContentStructureRedirectStrategy:
        tags:
            - { name: ibexa.admin_ui.focus_mode.redirect_strategy, priority: -90 }

    Ibexa\AdminUi\Strategy\FocusMode\OriginalPathRedirectStrategy:
        tags:
            - { name: ibexa.admin_ui.focus_mode.redirect_strategy, priority: -100 }
