parameters:
    ibexa.site_access.config.admin_group.user_settings_update_view_defaults:
        full:
            default:
                template: "@@ibexadesign/account/settings/update.html.twig"
                match: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\UserSetting\Autosave:
        tags:
            - { name: ibexa.user.setting.value, identifier: autosave, group: content_edit, priority: 30 }
            - { name: ibexa.user.setting.mapper.form, identifier: autosave }

    Ibexa\AdminUi\UserSetting\AutosaveInterval:
        tags:
            - { name: ibexa.user.setting.value, identifier: autosave_interval, group: content_edit, priority: 20 }
            - { name: ibexa.user.setting.mapper.form, identifier: autosave_interval }

    Ibexa\AdminUi\UserSetting\InContextTranslation:
        tags:
            - { name: ibexa.user.setting.value, identifier: in_context_translation, group: location, priority: 60 }
            - { name: ibexa.user.setting.mapper.form, identifier: in_context_translation }

    Ibexa\AdminUi\UserSetting\Group\UserModeGroup:
        tags:
            - { name: ibexa.user.setting.group, identifier: mode, priority: -10 }

    Ibexa\AdminUi\UserSetting\FocusMode:
        tags:
            - { name: ibexa.user.setting.value, identifier: focus_mode, group: mode, priority: 10 }
            - { name: ibexa.user.setting.mapper.form, identifier: focus_mode }
