services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Validator\Constraints\:
        resource: "../../../../lib/Validator/Constraints"

    Ibexa\AdminUi\Validator\Constraints\LocationIsWithinCopySubtreeLimitValidator:
        arguments:
            $configResolver: '@ibexa.config.resolver'

    Ibexa\AdminUi\Validator\Constraints\UniqueContentTypeIdentifierValidator:
        arguments: ['@ibexa.api.service.content_type']
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.unique_content_type_identifier }

    Ibexa\AdminUi\Validator\Constraints\FieldTypeValidator:
        class: Ibexa\AdminUi\Validator\Constraints\FieldTypeValidator
        arguments: ['@ibexa.api.service.field_type']
        abstract: true
        autoconfigure: false

    Ibexa\AdminUi\Validator\Constraints\ValidatorConfigurationValidator:
        parent: Ibexa\AdminUi\Validator\Constraints\FieldTypeValidator
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.validator_configuration }

    Ibexa\AdminUi\Validator\Constraints\FieldSettingsValidator:
        parent: Ibexa\AdminUi\Validator\Constraints\FieldTypeValidator
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.field_settings }

    Ibexa\AdminUi\Validator\Constraints\UniqueURLValidator:
        arguments:
            - '@ibexa.api.service.url'
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.unique_url }

