parameters:
    ibexa.site_access.config.default.content_type.about:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#info-square'
    ibexa.site_access.config.default.content_type.article:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#file-text'
    ibexa.site_access.config.default.content_type.blog:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#app-blog'
    ibexa.site_access.config.default.content_type.blog_post:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#note-blog'
    ibexa.site_access.config.default.content_type.folder:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#folder'
    ibexa.site_access.config.default.content_type.form:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#form-checkbox-square'
    ibexa.site_access.config.default.content_type.place:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#place' # TODO: missing icon
    ibexa.site_access.config.default.content_type.product:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#product'
    ibexa.site_access.config.default.content_type.field:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#form-input'
    ibexa.site_access.config.default.content_type.user:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#user'
    ibexa.site_access.config.default.content_type.user_group:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#user-group'
    ibexa.site_access.config.default.content_type.file:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#file'
    ibexa.site_access.config.default.content_type.gallery:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#image-gallery'
    ibexa.site_access.config.default.content_type.image:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#image'
    ibexa.site_access.config.default.content_type.video:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#video-play'
    ibexa.site_access.config.default.content_type.landing_page:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#layout-navbar'
    ibexa.site_access.config.default.content_type.editor:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#user-editor'
    ibexa.site_access.config.default.content_type.default-config:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#file'

    ibexa.site_access.config.default.content_type_group.default-config:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#file'
    ibexa.site_access.config.default.content_type_group.content:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#content-type-content' # TODO: missing icon
    ibexa.site_access.config.default.content_type_group.users:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#user-type' # TODO: missing icon
    ibexa.site_access.config.default.content_type_group.media:
        thumbnail: '/bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg#media-type' # TODO: missing icon

    ibexa.content_view.tabs.default_template: '@@ibexadesign/ui/tab/default.html.twig'

    ibexa.multifile_upload.location.mappings: []

    ibexa.multifile_upload.location.default_mappings:
        # Image
        - mime_types:
              - image/jpeg
              - image/jpg
              - image/pjpeg
              - image/pjpg
              - image/png
              - image/bmp
              - image/gif
              - image/tiff
              - image/x-icon
              - image/webp
          content_type_identifier: image
          content_field_identifier: image
          name_field_identifier: name
        # File
        - mime_types:
              - image/svg+xml
              - application/msword
              - application/vnd.openxmlformats-officedocument.wordprocessingml.document
              - application/vnd.ms-excel
              - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
              - application/vnd.ms-powerpoint
              - application/vnd.openxmlformats-officedocument.presentationml.presentation
              - application/pdf
          content_type_identifier: file
          content_field_identifier: file
          name_field_identifier: name

    ibexa.multifile_upload.fallback_content_type:
        content_type_identifier: file
        content_field_identifier: file
        name_field_identifier: name

    ibexa.io.multifile_upload.max_file_size: 5242880

    ibexa.admin_ui.content_tree.node_factory.max_location_ids_in_single_aggregation: 100

    ibexa.site_access.config.default.admin_ui.default_focus_mode: '1'

    #### DAM WIDGET
    ibexa.dam_widget.image.mappings:
        image:
            imageFieldIdentifier: image
            tagsFieldIdentifier: tags
            descriptionFieldIdentifier: description

    ibexa.dam_widget.image.aggregations:
        KeywordTermAggregation:
            name: keywords
            contentTypeIdentifier: image
            fieldDefinitionIdentifier: tags

    ibexa.dam_widget.image.download_limit: 25

    ibexa.dam_widget.folder.content_type_identifier: folder
