system:
    admin_group:
        assets:
            icon_aliases:
                about-info: help
                about: info-square
                airtime: signal-radio
                align-center: align-text-center
                align-justify: align-text-justified
                align-left: align-text-left
                align-right: align-text-right
                approved: check-circle
                article: file-text
                assign-section: assign
                author: user-editor
                autosave-error: cloud-error
                autosave-off: cloud-discard
                autosave-on: cloud
                autosave-saved: cloud-check
                autosave-saving: cloud-synch
                b2b: handshake
                back: arrow-left
                back-current-date: calendar-back
                bestseller: badge-star
                block-invisible: block-hidden
                block-visible-recurring: block-lock
                blog: app-blog
                blog_post: note-blog
                bold: text-bold
                bookmark: favourite-outline
                bookmark-active: favourite-filled
                bookmark-manager: book
                box-collapse: arrow-move-right
                browse: folder-browse
                bubbles: message-bubble
                business-deal-cash: user-money
                button: cursor-clicked
                campaign: speaker
                captcha: form-captcha
                caret-back: arrow-chevron-left
                caret-double-back: arrow-double-left
                caret-double-next: arrow-double-right
                caret-down: arrow-chevron-down
                caret-expanded: arrow-double-left
                caret-next: arrow-chevron-right
                caret-up: arrow-chevron-up
                cart: shopping-cart
                cart-full: shopping-cart
                cart-upload: shopping-cart-arrow-up
                cart-wishlist: shopping-cart-heart
                category: tag
                checkbox: form-checkbox
                checkbox-multiple: form-check-list
                checkmark: form-check
                circle-caret-down: chevron-down-circle
                circle-caret-left: chevron-left-circle
                circle-caret-right: chevron-right-circle
                circle-caret-up: chevron-up-circle
                circle-close: discard-circle
                circle-create: add-circle
                circle-minus: minus-circle
                circle-pause: minus-circle
                clicked-recommendations: cursor-clicked-hand
                clipboard: clipboard-check
                collapse: arrow-collapse-right
                content-write: file-text-write
                column-settings: table-settings-column
                comment: message
                components: box-component
                connect: connection
                content-draft: draft
                contentlist: list-content
                content-list: list-content
                content-type: tools
                content-type-content: file-type
                content-type-group: tool-group
                copy-subtree: content-tree-copy
                create: add
                create-content: file-add
                create-location: content-tree-create-location
                customer: user-customer
                customer-portal: device-monitor-user
                customer-portal-page: app-user
                customer-type: device-monitor-type
                custom_tags: prompt
                date: calendar
                date-updated: calendar-reload
                discount-coupon: discount-ticket
                drafts: edit-draft
                dropdown: form-dropdown
                earth-access: world-cursor
                embed: text-embedded
                embed-inline: text-embedded-inline
                erp: connection-erp
                error: exclamation-mark
                error-icon: file-warning
                expand-left: arrow-expand-left
                expand-right: arrow-expand-right
                explore: ai
                fields: form-input
                file-video: video
                flash: lightning
                focus: arrows-outside
                focus-image: focus-target
                folder-empty: folder-open
                form: form-check-square
                full-view: arrows-full-view
                future-publication: calendar-clock
                gallery: image-gallery
                go-right: arrow-to-right
                go-to-root: content-tree-arrow-up
                go-up: arrow-to-up
                h1: header-1
                h2: header-2
                h3: header-3
                h4: header-4
                h5: header-5
                h6: header-6
                hide: visibility-hidden
                hierarchy: hierarchy-site-map
                history-file: file-history
                'home-page': home
                image-center: align-block-center
                image-editor: image-edit
                image-left: align-block-left
                image-right: align-block-right
                image-variations: image-focus
                imported-items: database-synch
                information: info-square
                input-hidden: form-input-hidden
                input-line: form-input-single-line
                input-line-multiple: form-input-multi-line
                input-number: form-input-number
                interface-block: forbidden
                italic: text-italic
                keyword: hash
                landing_page: layout-navbar
                landingpage-add: layout-navbar-add
                landingpage-preview: layout-navbar-visible
                languages: world
                languages-add: world-add
                last-purchased: cursor-clicked-hand
                last-viewed: app-recent
                layout-manager: layout
                link-content: file-link
                link-remove: unlink
                list: list-bullet
                list-numbered: list-number
                localize: target-location
                location-add-new: content-tree-create-location
                lock-unlock: unlock
                logout: log-out
                maform: chart-histogram
                mail: message-email
                mail-open: message-email-read
                markup: file-code
                menu: menu-hamburger
                move: folder-open-move
                newsletter: news
                notice: alert-error
                open-newtab: open-new-window
                open-sametab: open-same-window
                options: more
                order-history: file-history
                order-management: receipt-settings
                order-status: product-search
                panels: view-panels
                paragraph: text-paragraph
                paragraph-add: text-paragraph-add
                pdf-file: file-pdf
                personalize: user-target
                personalize-block: file-settings
                personalize-content: tag-settings
                pin-unpin: unpin
                place: pin-location
                places: pins-locations
                portfolio: suitcase
                previewed: overdue
                product-category: product-tag
                product-list: clipboard-list
                product_list: clipboard-list
                product-low: product-arrow-down
                product type: product-collection
                product-type: product-collection
                profile: user-profile
                publish: rocket
                publish-later: calendar-number
                publish-later-cancel: calendar-discard
                publish-later-create: calendar-add
                qa-content: qa-file
                qa-form: qa-form-check
                radio-button: form-radio
                radio-button-multiple: form-radio-list
                rate: stars
                rate-review: star-circle
                recent-activity: activity-clock
                recently-added: history
                recommendation-calls: arrows-circle
                redo: action-redo
                refresh: arrows-reload
                rejected: arrow-to-down-circle
                relations: hierarchy-square
                restore: arrow-restore
                restore-parent: content-tree-restore-parent
                review: message-edit
                roles: user-id
                rss: signal-rss
                schedule: calendar-schedule
                sections: database
                send-email: send
                settings-block: settings
                settings-config: settings-configure
                sites-all: sites
                spinner: arrow-rotate
                stats: chart-dots
                strikethrough: text-strikethrough
                subscriber: user-mail
                subscript: text-subscript
                superscript: text-superscript
                swap: arrows-synchronize
                system-information: info-circle
                trash-empty: trash-discard
                trash-notrashed: trash-open
                underscore: text-underline
                undo: action-undo
                un-focus: arrows-inside
                un-full-view: arrows-full-view-out
                upload-image: image-upload
                user-blocked: user-block
                user_group: user-group
                users-personalization: user-focus
                user-recycle: arrows-reload-user
                users-select: users-add
                user-tick: user-check
                version-compare: action-compare-versions
                version-compare-action: action-compare
                versions: archived-version
                vertical-left-right: arrow-collapse-expand
                view: visibility
                view-desktop: device-monitor
                view-hide: visibility-hidden
                view-mobile: device-mobile
                view-tablet: device-tablet
                warning: alert-warning
                warning-triangle: alert-warning
