system:
    admin_group:
        assets:
            icon_sets:
                ids_icons: /bundles/ibexaadminuiassets/vendors/ids-assets/dist/img/all-icons.svg
            default_icon_set: ids_icons