system:
    admin_group:
        assets:
            icon_aliases:
                about-info: info-hexa
                about: info-square
                activate: activate
                airtime: signal-radio
                align-center: align-text-center
                align-justify: align-text-justified
                align-left: align-text-left
                align-right: align-text-right
                archive-restore: archived-restore
                arrow-down: arrow-caret-down
                arrow-right: arrow-caret-right
                article: file-text
                assign-section: assign
                assign-user: assign-user
                author: user-editor
                autosave-error: cloud-error
                autosave-off: cloud-discard
                autosave-on: cloud
                autosave-saved: cloud-check
                autosave-saving: cloud-synch
                b2b: handshake
                back: arrow-left
                back-current-date: calendar-back
                banner: banner
                bell: bell
                bestseller: badge-star
                block-add: block-add
                block-invisible: calendar-invisible
                block-visible: calendar-visible
                block-visible-recurring: calendar-block
                blog: app-blog
                blog_post: note-blog
                bold: text-bold
                bookmark: favourite
                bookmark-active: favourite-filled
                bookmark-manager: book
                browse: folder-browse
                business-deal-cash: user-money
                button: cursor-clicked
                campaign: speaker
                caret-back: arrow-chevron-back
                caret-double-back: arrow-double-left
                caret-double-next: arrow-double-right
                caret-down: arrow-chevron-down
                caret-expanded: arrow-double-left
                caret-next: arrow-chevron-right
                caret-up: arrow-chevron-up
                cart: shopping-cart
                catalog: catalog
                category: tag
                checkbox: form-checkbox
                checkbox-multiple: form-check-list
                checkmark: form-check
                circle-close: discard-circle
                circle-create: plus-circle
                circle-pause: minus-circle
                clicked-recommendations: cursor-clicked-hand
                collapse: arrow-collapse-right
                collection: collection
                column-settings: table-settings-column
                comment: message
                company: company
                components: box-component
                connect: connection
                content-draft: draft
                contentlist: list-content
                content-tree: content-tree
                content-type: tools
                content-type-group: tool-group
                copy: copy
                copy-subtree: content-tree-copy
                create: add
                create-content: file-add
                create-location: content-tree-create-location
                crop: crop
                customer: user-customer
                customer-portal: device-monitor-user
                customer-portal-page: app-user
                custom_tags: prompt
                database: database
                dectivate: deactivate
                discard: discard
                discount-coupon: discount-ticket
                download: download
                drafts: edit-draft
                drag: drag
                dropdown: form-dropdown
                earth-access: world-coursor
                edit: edit
                embed: text-embeded
                error-icon: file-warning
                expand-left: arrow-expand-left
                expand-right: arrow-expand-right
                explore: ai
                facebook: facebook
                fields: form-input
                file: file
                file-text: file-txt-other
                filters: filters
                flag: flag
                flash: lightning
                flip-horizontal: flip-horizontal
                flip-vertical: flip-vertical
                focus: arrows-outside
                focus-image: focus-target
                folder: folder
                form: form-checkbox-square
                full-view: arrow-full-view
                future-publication: calendar-clock
                gallery: image-gallery
                go-right: arrow-to-right
                go-to-root: content-tree-arrow-up
                go-up: arrow-to-up
                h1: header
                hide: eye-no-visibility
                hierarchy: hierarchy-site-map
                history: history
                history-file: file-history
                home-page: home
                image: image
                image-center: align-block-center
                image-left: align-block-left
                image-right: align-block-right
                imported-items: database-sync
                input-line: form-input-single-line
                input-line-multiple: form-input-multi-line
                input-number: form-input-number
                interface-block: forbidden
                italic: text-italic
                keyword: hash
                landing_page: layout-navbar
                landingpage-add: layout-navbar-plus
                languages: world
                languages-add: world-plus
                last-purchased: cursor-clicked-hand
                layout-switch: layout-switch
                link: link
                link-anchor: link-anchor
                link-remove: unlink
                list: list-bullet
                list-numbered: list-number
                localize: target-location
                location-add-new: content-tree-create-location
                lock: lock
                lock-unlock: unlock
                logout: log-out
                mail-open: message-mail-read
                markup: file-code
                menu: menu-hamburger
                merge: merge
                move: folder-open-move
                news: news
                notice: alert-error
                open-newtab: open-new-window
                open-sametab: open-same-window
                options: more
                order-history: file-history
                order-management: receipt-settings
                order-status: product-search
                panels: view-panels
                paragraph: text-paragraph
                personalize: user-target
                personalize-block: file-settings
                personalize-content: tag-settings
                product: product
                product-catalog: product-catalog
                product-category: product-tag
                product-low: product-arrow-down
                product type: product-collection
                profile: user-profile
                publish-later: calendar-number
                radio-button: form-radio
                radio-button-multiple: form-radio-list
                recent-activity: activity-clock
                redo: action-redo
                refresh: arrows-reloaded
                restore: arrow-restore
                roles: user-id
                save: save
                schedule: calendar-schedule
                search: search
                sections: database
                seen this: seen-this
                segments: segments
                settings-block: settings
                settings-config: settings-configure
                share: share
                sites: sites
                strikethtough: text-strikethrough
                subscript: text-subscript
                superscript: text-superscript
                system-information: info-circle
                table-add: table-plus
                table-cell: table-cell
                table-column: table-column
                table-row: table-row
                tag: text-code
                tags: tags
                timeline: timeline
                trash: trash
                unarchive: unarchive
                underscore: text-underline
                undo: action-undo
                un-focus: arrows-inside
                un-full-view: arrows-full-view-out
                upload: upload
                upload-image: image-upload
                user: user
                user-blocked: user-block
                user_group: user-group
                users-personalization: user-focus
                users-select: users-plus
                user-tick: user-check
                version-compare: action-compare-versions
                versions: archived-version
                video: video-play
                view: visibility
                view-grid: view-grid
                view-hide: invisibility
                view-list: view-list
                view-mobile: device-mobile
                view-tablet: device-tablet
                warning: alert-warning
                warning-triangle: alert-warning
                workflow: workflow
