imports:
    - { resource: services/service_aliases.yaml }
    - { resource: services/config.yaml }
    - { resource: services/controller_argument_resolvers.yaml }
    - { resource: services/controllers.yaml }
    - { resource: services/tabs.yaml }
    - { resource: services/menu.yaml }
    - { resource: services/pagination.yaml }
    - { resource: services/ui_config/* }
    - { resource: services/components.yaml }
    - { resource: services/dashboard.yaml }
    - { resource: services/modules/subitems.yaml }
    - { resource: services/modules/content_tree.yaml }
    - { resource: services/modules/field_type_toolbar.yaml }
    - { resource: services/form_processors.yaml }
    - { resource: services/validators.yaml }
    - { resource: services/services.yaml }
    - { resource: services/siteaccess.yaml }
    - { resource: services/universal_discovery_widget.yaml }
    - { resource: services/utils.yaml }
    - { resource: services/form_ui_action_mappers.yaml }
    - { resource: services/views.yaml }
    - { resource: services/translation.yaml }
    - { resource: services/user_profile.yaml }
    - { resource: services/user_settings.yaml }
    - { resource: services/rest.yaml }
    - { resource: services/permissions.yaml }
    - { resource: services/forms.yaml }
    - { resource: services/strategies.yaml }
    - { resource: services/query_types.yaml }
    - { resource: services/role_form_mappers.yaml }
    - { resource: services/fieldtype_form_mappers.yaml }
    - { resource: services/action_dispatchers.yaml }
    - { resource: services/events.yaml }
    - { resource: services/twig.yaml }
    - { resource: services/autosave.yaml }
    - { resource: services/user.yaml }
    - { resource: services/commands.yaml }
    - { resource: services/icons.yaml }
    - { resource: services/role_form_mappers.yaml }
    - { resource: services/security.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Contracts\AdminUi\Controller\Controller:
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    Ibexa\Bundle\AdminUi\ParamConverter\:
        resource: "../../ParamConverter/*"
        public: true
        tags:
            - { name: 'request.param_converter' }

    Ibexa\Bundle\AdminUi\ParamConverter\ContentTypeParamConverter:
        public: true
        tags:
            - { name: 'request.param_converter' }

    Ibexa\AdminUi\UI\Dataset\DatasetFactory:
        lazy: true
        arguments:
            $configResolver: '@ibexa.config.resolver'
        tags:
            - { name: 'monolog.logger', channel: 'ibexa.admin_ui' }

    Ibexa\AdminUi\UI\Service\:
        resource: '../../../lib/UI/Service'

    Ibexa\AdminUi\UI\Value\Content\Location\Mapper: ~

    Ibexa\AdminUi\UI\Value\ValueFactory:
        lazy: true
        tags:
            - { name: form.type }

    Ibexa\AdminUi\Form\SubmitHandler:
        decorates: Ibexa\User\Form\BaseSubmitHandler

    Ibexa\AdminUi\Notification\FlashBagNotificationHandler: ~
    Ibexa\AdminUi\Notification\TranslatableNotificationHandler:
        decorates: Ibexa\User\ExceptionHandler\NullActionResultHandler

    Ibexa\Contracts\AdminUi\Notification\NotificationHandlerInterface: '@Ibexa\AdminUi\Notification\FlashBagNotificationHandler'
    Ibexa\Contracts\AdminUi\Notification\TranslatableNotificationHandlerInterface: '@Ibexa\AdminUi\Notification\TranslatableNotificationHandler'

    Ibexa\AdminUi\Menu\Voter\LocationVoter:
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.voter }

    Ibexa\AdminUi\Form\ActionDispatcher\CreateContentOnTheFlyDispatcher:
        parent: Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher
        autowire: true
        autoconfigure: false
        public: false

    Ibexa\AdminUi\Form\ActionDispatcher\CreateUserOnTheFlyDispatcher:
        parent: Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher
        autowire: true
        autoconfigure: false
        public: false

    Ibexa\AdminUi\Form\ActionDispatcher\EditContentOnTheFlyDispatcher:
        parent: Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher
        autowire: true
        autoconfigure: false
        public: false

    Ibexa\AdminUi\Form\ActionDispatcher\EditUserOnTheFlyDispatcher:
        parent: Ibexa\ContentForms\Form\ActionDispatcher\AbstractActionDispatcher
        autowire: true
        autoconfigure: false
        public: false

    Ibexa\AdminUi\EventListener\MenuPermissionsListener:
        tags:
            - {name: kernel.event_subscriber, priority: -250}

    Ibexa\AdminUi\EventListener\CredentialsExpiredListener:
        arguments:
            $siteAccessGroups: '%ibexa.site_access.groups%'
        tags:
            - {name: kernel.event_subscriber}

    Ibexa\AdminUi\EventListener\CredentialsExpirationWarningListener:
        arguments:
            $siteAccessGroups: '%ibexa.site_access.groups%'
        tags:
            - {name: kernel.event_subscriber}

    Ibexa\Bundle\AdminUi\Templating\Twig\UserPreferencesGlobalExtension:
        lazy: true

    Ibexa\AdminUi\UI\Service\IconResolver:
        abstract: true

    Ibexa\AdminUi\UI\Service\ContentTypeIconResolver:
        parent: Ibexa\AdminUi\UI\Service\IconResolver

    Ibexa\AdminUi\UI\Service\ContentTypeGroupIconResolver:
        parent: Ibexa\AdminUi\UI\Service\IconResolver

    Ibexa\ContentForms\ConfigResolver\MaxUploadSize: ~

    Ibexa\AdminUi\Form\Data\FormMapper\ContentTypeDraftMapper: ~

    Ibexa\AdminUi\UI\Service\DateTimeFormatter: ~
    Ibexa\AdminUi\UI\Service\DateTimeFormatterInterface: '@Ibexa\AdminUi\UI\Service\DateTimeFormatter'

    Ibexa\AdminUi\EventListener\SearchViewFilterParametersListener:
        arguments:
            $formFactory: '@form.factory'
            $configResolver: '@ibexa.config.resolver'
            $requestStack: '@request_stack'
            $siteAccessGroups: '%ibexa.site_access.groups%'
        tags:
            - {name: kernel.event_subscriber}
