Ibexa\AdminUi\Form\Data\Section\SectionCreateData:
    properties:
        identifier:
            - NotBlank: ~
            - Regex:
                pattern: "/^[[:alnum:]_]+$/"
                message: "ez.section.identifier.format"
        name:
            - NotBlank: ~

Ibexa\AdminUi\Form\Data\Section\SectionUpdateData:
    properties:
        identifier:
            - NotBlank: ~
            - Regex:
                pattern: "/^[[:alnum:]_]+$/"
                message: "ez.section.identifier.format"
        name:
            - NotBlank: ~