parameters:
    # Limitation mappers
    ibexa.content_forms.limitation.null.template: "@@ibexadesign/limitation/null_limitation_values.html.twig"
    ibexa.content_forms.limitation.udw.template: "@@ibexadesign/limitation/udw_limitation_value.html.twig"
    ibexa.content_forms.limitation.multiple_selection.template: "@@ibexadesign/limitation/base_limitation_values.html.twig"
