services:
    Ibexa\AdminUi\Tab\ContentType\:
        resource: "../../../lib/Tab/ContentType/*"
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractEventDispatchingTab
        public: true
        tags:
            - { name: ezplatform.tab, group: content-type }

    ezplatform.adminui.content_type.tab_groups:
        parent: Ibexa\AdminUi\Component\TabsComponent
        arguments:
            $template: '@@ezdesign/ui/tab/content_type.html.twig'
            $groupIdentifier: 'content-type'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'content-type-tab-groups' }
