name: Assign frontend reviewers

on:
  pull_request:
    types: [ labeled, synchronize ]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

     steps:
      - name: Set up GitHub CLI
        uses: cli/gh-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add reviewers from team (excluding author)
        run: |
          ORG="ibexa"
          TEAM="javascript-dev"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"

          echo "Fetching members of team $ORG/$TEAM..."
          TEAM_MEMBERS=$(gh api "/orgs/$ORG/teams/$TEAM/members" --paginate -q '.[].login')