name: Frontend build

on:
    push:
        paths:
            - "**.cjs"
            - "**.mjs"
            - "**.js"
            - "**.jsx"
            - "**.ts"
            - "**.tsx"
            - "**.scss"
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request:
        paths:
            - "**.cjs"
            - "**.mjs"
            - "**.js"
            - "**.jsx"
            - "**.ts"
            - "**.tsx"
            - "**.scss"

jobs:
    frontend-test:
        name: Frontend build test
        runs-on: 'ubuntu-26.04'
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v6
              with:
                  node-version: '24'
            - uses: ibexa/gh-workflows/actions/setup-composer-root-version@main
            - uses: ibexa/gh-workflows/actions/composer-install@main
              with:
                  gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                  gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                  satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
                  satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}
            - run: yarn install
            - uses: ibexa/gh-workflows/actions/yarn-test@main
