services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Form\ActionDispatcher\ContentTypeDispatcher:
        parent: ezplatform.content_forms.action_dispatcher.base
        autowire: true
        autoconfigure: false
        public: false
