services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\AdminUi\Menu\Action\ContentAwareActionItemFactory: ~

    Ibexa\Contracts\AdminUi\Menu\ContentAwareActionItemFactoryInterface:
        alias: Ibexa\AdminUi\Menu\Action\ContentAwareActionItemFactory

    Ibexa\AdminUi\Menu\Action\DraftListActionMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ibexa.admin_ui.action.draft_list }

    Ibexa\AdminUi\Menu\Action\VersionListActionMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ibexa.admin_ui.action.version_list }
