services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\AdminUi\Autosave\AutosaveService: ~

    Ibexa\Contracts\AdminUi\Autosave\AutosaveServiceInterface:
        alias: Ibexa\AdminUi\Autosave\AutosaveService

    Ibexa\AdminUi\EventListener\ContentProxyCreateDraftListener: ~

    Ibexa\AdminUi\Form\Processor\Content\AutosaveProcessor:
        arguments:
            $innerContentFormProcessor: '@Ibexa\ContentForms\Form\Processor\ContentFormProcessor'
        tags:
            - { name: kernel.event_subscriber }
