services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Bundle\AdminUi\Command\CompileAssetsCommand:
        tags:
            - { name: console.command }
