services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\EventListener\:
        resource: "../../../../lib/EventListener/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\RequestListener:
        arguments:
            - '%ibexa.site_access.groups_by_site_access%'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\RequestLocaleListener:
        arguments:
            $siteAccessGroups: '%ibexa.site_access.groups%'
            $availableTranslations: '%available_translations%'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\RequestAttributesListener:
        arguments:
            - '%ibexa.site_access.groups%'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\AdminExceptionListener:
        arguments:
            $siteAccessGroups: '%ibexa.site_access.groups%'
            $kernelProjectDir: '%kernel.project_dir%'
            $kernelEnvironment: '%kernel.environment%'
            $encoreTagRenderer: '@webpack_encore.tag_renderer'
            $entrypointLookupCollection: '@webpack_encore.entrypoint_lookup_collection'
            $logLevel: 'error'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            - { name: monolog.logger, channel: ibexa.admin }

    Ibexa\AdminUi\EventListener\MenuPermissionsListener:
        tags:
            - { name: kernel.event_subscriber, priority: -250 }

    Ibexa\AdminUi\EventListener\ViewTemplatesListener:
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\ContentDownloadRouteReferenceListener:
        arguments:
            $siteAccessGroups: '%ibexa.site_access.groups%'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\SetViewParametersListener:
        arguments:
            $groupedContentFormFieldsProvider: '@Ibexa\AdminUi\Form\Provider\GroupedNonMetaFormFieldsProvider'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\InContextTranslationListener:
        arguments:
            $siteAccessGroups: '%ibexa.site_access.groups%'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\UserProfileListener:
        tags:
            - { name: kernel.event_subscriber }
