services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\EventListener\:
        resource: "../../../lib/EventListener/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\RequestListener:
        arguments:
            - '%ezpublish.siteaccess.groups_by_siteaccess%'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\RequestLocaleListener:
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
            $availableTranslations: '%available_translations%'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\RequestAttributesListener:
        arguments:
            - '%ezpublish.siteaccess.groups%'
        tags:
            - {name: kernel.event_subscriber}

    Ibexa\AdminUi\EventListener\AdminExceptionListener:
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
            $kernelProjectDir: '%kernel.project_dir%'
            $kernelEnvironment: '%kernel.environment%'
            $encoreTagRenderer: '@webpack_encore.tag_renderer'
            $entrypointLookupCollection: '@webpack_encore.entrypoint_lookup_collection'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Ibexa\AdminUi\EventListener\MenuPermissionsListener:
        tags:
            - {name: kernel.event_subscriber, priority: -250}

    Ibexa\AdminUi\EventListener\ViewTemplatesListener:
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\EventListener\ContentDownloadRouteReferenceListener:
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
        tags:
            - {name: kernel.event_subscriber}
