services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\UI\Action\EventDispatcher: ~
    Ibexa\Contracts\AdminUi\UI\Action\EventDispatcherInterface: '@Ibexa\AdminUi\UI\Action\EventDispatcher'

    Ibexa\AdminUi\UI\Action\FormUiActionMapper:
        tags:
            - { name: ezplatform.admin_ui.form_ui_action_mapper }

    Ibexa\Contracts\AdminUi\UI\Action\FormUiActionMapperInterface:
        alias: 'Ibexa\AdminUi\UI\Action\FormUiActionMapper'

    Ibexa\AdminUi\UI\Action\FormUiActionMappingDispatcher:
        arguments:
            $mappers: !tagged ezplatform.admin_ui.form_ui_action_mapper
            $defaultMapper: '@Ibexa\AdminUi\UI\Action\FormUiActionMapper'
