services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Ibexa\AdminUi\Form\TrashLocationOptionProvider\TrashLocationOptionProvider:
            tags: [ ibexa.admin_ui.form.trash_location_option ]

    Ibexa\AdminUi\Form\SubmitHandler: ~

    Ibexa\AdminUi\Form\Factory\ContentTypeFormFactory: ~

    Ibexa\AdminUi\Form\Factory\FormFactory: ~

    Ibexa\AdminUi\Form\Factory\TrashFormFactory: ~

    Ibexa\AdminUi\Form\DataMapper\ContentMainLocationUpdateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\LanguageCreateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\MainTranslationUpdateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\PolicyCreateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\PolicyUpdateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\RoleCopyMapper: ~

    Ibexa\AdminUi\Form\DataMapper\RoleCreateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\RoleUpdateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\SectionCreateMapper: ~

    Ibexa\AdminUi\Form\DataMapper\SectionUpdateMapper: ~

    Ibexa\AdminUi\Form\Type\Bookmark\BookmarkRemoveType: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\AvailableTranslationLanguageChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\BaseTranslationLanguageChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ConfiguredLanguagesChoiceLoader:
        arguments:
            $configResolver: '@ibexa.config.resolver'

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ContentCreateContentTypeChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ContentCreateLanguageChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ContentEditTranslationChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\DatePeriodChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader:
        arguments:
            $configResolver: '@ibexa.config.resolver'

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\SiteAccessChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\Content\ContentInfoType: ~

    Ibexa\AdminUi\Form\Type\Content\ContentType: ~

    Ibexa\AdminUi\Form\Type\Content\ContentTypeSubmitType: ~

    Ibexa\AdminUi\Form\Type\Content\ContentTypeType: ~

    Ibexa\AdminUi\Form\Type\Content\ContentVisibilityUpdateType: ~

    Ibexa\AdminUi\Form\Type\Content\CustomUrl\CustomUrlAddType: ~

    Ibexa\AdminUi\Form\Type\Content\CustomUrl\CustomUrlRemoveType: ~

    Ibexa\AdminUi\Form\Type\Content\Draft\ContentCreateType:
        arguments:
            $contentTypeChoiceLoader: '@Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader'
            $languageChoiceLoader: '@Ibexa\AdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader'

    Ibexa\AdminUi\Form\Type\Content\Draft\ContentEditType: ~

    Ibexa\AdminUi\Form\Type\Content\Draft\ContentRemoveType: ~

    Ibexa\AdminUi\Form\Type\Content\Location\ContentLocationAddType: ~

    Ibexa\AdminUi\Form\Type\Content\Location\ContentLocationRemoveType: ~

    Ibexa\AdminUi\Form\Type\Content\Location\ContentMainLocationUpdateType: ~

    Ibexa\AdminUi\Form\Type\Content\LocationType: ~

    Ibexa\AdminUi\Form\Type\Content\SortType: ~

    Ibexa\AdminUi\Form\Type\Content\Translation\MainTranslationUpdateType: ~

    Ibexa\AdminUi\Form\Type\Content\Translation\TranslationAddType: ~

    Ibexa\AdminUi\Form\Type\Content\Translation\TranslationDeleteType: ~

    Ibexa\AdminUi\Form\Type\Content\VersionInfoType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeChoiceType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeCopyType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeCreateType:
        arguments: ['@ibexa.api.service.content_type']
        tags:
            - {name: form.type, alias: ezplatform_content_forms_contenttype_create}

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeDeleteType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeEditType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeGroupDeleteType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeGroupType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeUpdateType:
        tags:
            - {name: form.type, alias: ezplatform_content_forms_contenttype_update}

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypesDeleteType: ~

    Ibexa\AdminUi\Form\Type\ContentType\FieldTypeChoiceType:
        arguments: ['@Ibexa\Core\FieldType\FieldTypeRegistry', '@translator']
        tags:
            - { name: form.type, alias: ezplatform_content_forms_contenttype_field_type_choice }

    Ibexa\AdminUi\Form\Type\ContentType\SortFieldChoiceType:
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: ezplatform_content_forms_contenttype_sort_field_choice }

    Ibexa\AdminUi\Form\Type\ContentType\SortOrderChoiceType:
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: ezplatform_content_forms_contenttype_sort_order_choice }

    Ibexa\AdminUi\Form\Type\ContentType\Translation\TranslationAddType: ~

    Ibexa\AdminUi\Form\Type\ContentType\Translation\TranslationRemoveType: ~

    Ibexa\AdminUi\Form\Type\ContentTypeGroup\ContentTypeGroupCreateType: ~

    Ibexa\AdminUi\Form\Type\ContentTypeGroup\ContentTypeGroupDeleteType: ~

    Ibexa\AdminUi\Form\Type\ContentTypeGroup\ContentTypeGroupType: ~

    Ibexa\AdminUi\Form\Type\ContentTypeGroup\ContentTypeGroupUpdateType: ~

    Ibexa\AdminUi\Form\Type\ContentTypeGroup\ContentTypeGroupsDeleteType: ~

    Ibexa\AdminUi\Form\Type\Date\DateIntervalType: ~

    Ibexa\AdminUi\Form\Type\DateTimeIntervalType: ~

    Ibexa\AdminUi\Form\Type\DateTimePickerType: ~

    Ibexa\AdminUi\Form\Type\Embedded\SectionType: ~

    Ibexa\AdminUi\Form\Type\Extension\Content\ContentEditTypeExtension:
        tags:
            - { name: form.type_extension }

    Ibexa\AdminUi\Form\Type\FieldDefinition\FieldDefinitionType:
        arguments:
            $fieldTypeService: '@ibexa.api.service.field_type'
            $thumbnailStrategy: '@Ibexa\Core\Repository\Strategy\ContentThumbnail\Field\ContentFieldStrategy'
        calls:
            - [setGroupsList, ['@Ibexa\Core\Helper\FieldsGroups\ArrayTranslatorFieldsGroupsList']]
        tags:
            - { name: form.type, alias: ezplatform_content_forms_fielddefinition_update }

    Ibexa\AdminUi\Form\Type\FieldDefinition\User\PasswordConstraintCheckboxType: ~

    Ibexa\AdminUi\Form\Type\Language\ConfiguredLanguagesChoiceType: ~

    Ibexa\AdminUi\Form\Type\Language\LanguageChoiceType: ~

    Ibexa\AdminUi\Form\Type\Language\LanguageCreateType: ~

    Ibexa\AdminUi\Form\Type\Language\LanguageDeleteType: ~

    Ibexa\AdminUi\Form\Type\Language\LanguageType: ~

    Ibexa\AdminUi\Form\Type\Language\LanguageUpdateType: ~

    Ibexa\AdminUi\Form\Type\Language\LanguagesDeleteType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationAssignSectionType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationCopySubtreeType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationCopyType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationMoveType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationSwapType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationTrashType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationUpdateType: ~

    Ibexa\AdminUi\Form\Type\Location\LocationUpdateVisibilityType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ContentObjectStateUpdateType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateChoiceType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateCreateType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateDeleteType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateGroupCreateType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateGroupDeleteType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateGroupType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateGroupUpdateType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateGroupsDeleteType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStateUpdateType: ~

    Ibexa\AdminUi\Form\Type\ObjectState\ObjectStatesDeleteType: ~

    Ibexa\AdminUi\Form\Type\Policy\PoliciesDeleteType: ~

    Ibexa\AdminUi\Form\Type\Policy\PolicyChoiceType:
        arguments:
            $policyMap: "%ezpublish.api.role.policy_map%"

    Ibexa\AdminUi\Form\Type\Policy\PolicyCreateType: ~

    Ibexa\AdminUi\Form\Type\Policy\PolicyCreateWithLimitationType: ~

    Ibexa\AdminUi\Form\Type\Policy\PolicyDeleteType: ~

    Ibexa\AdminUi\Form\Type\Policy\PolicyType: ~

    Ibexa\AdminUi\Form\Type\Policy\PolicyUpdateType: ~

    Ibexa\AdminUi\Form\Type\Role\LimitationType:
        arguments:
            - '@Ibexa\AdminUi\Limitation\LimitationFormMapperRegistry'
            - '@Ibexa\AdminUi\Limitation\Mapper\NullLimitationMapper'
        tags:
            - { name: form.type, alias: ezplatform_content_forms_policy_limitation_edit }

    Ibexa\AdminUi\Form\Type\Role\RoleAssignmentCreateType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleAssignmentDeleteType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleAssignmentType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleAssignmentsDeleteType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleCopyType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleCreateType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleDeleteType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleType: ~

    Ibexa\AdminUi\Form\Type\Role\RoleUpdateType: ~

    Ibexa\AdminUi\Form\Type\Role\RolesDeleteType: ~

    Ibexa\AdminUi\Form\Type\RoleAssignment\RoleAssignmentType: ~

    Ibexa\AdminUi\Form\Type\Search\DateIntervalType: ~

    Ibexa\AdminUi\Form\Type\Search\SearchType:
        arguments:
            $baseType: '@Ibexa\Bundle\Search\Form\Type\SearchType'
            $translator: '@translator'
        tags:
            - { name: form.type, alias: Ibexa\AdminUi\Form\Type\Search\SearchType }

    Ibexa\AdminUi\Form\Type\Search\TrashSearchType: ~

    Ibexa\AdminUi\Form\Type\Section\SectionChoiceType: ~

    Ibexa\AdminUi\Form\Type\Section\SectionContentAssignType: ~

    Ibexa\AdminUi\Form\Type\Section\SectionCreateType: ~

    Ibexa\AdminUi\Form\Type\Section\SectionDeleteType: ~

    Ibexa\AdminUi\Form\Type\Section\SectionType: ~

    Ibexa\AdminUi\Form\Type\Section\SectionUpdateType: ~

    Ibexa\AdminUi\Form\Type\Section\SectionsDeleteType: ~

    Ibexa\AdminUi\Form\Type\SwitcherType: ~

    Ibexa\AdminUi\Form\Type\Trash\ChoiceList\Loader\SearchContentTypeChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\Trash\TrashEmptyType: ~

    Ibexa\AdminUi\Form\Type\Trash\TrashItemCheckboxType: ~

    Ibexa\AdminUi\Form\Type\Trash\TrashItemDeleteType: ~

    Ibexa\AdminUi\Form\Type\Trash\TrashItemRestoreType: ~

    Ibexa\AdminUi\Form\Type\URL\URLEditType:
        tags:
            - { name: form.type, alias: ezplatform_content_forms_url_edit }

    Ibexa\AdminUi\Form\Type\URL\URLListType:
        arguments:
            - '@translator'
        tags:
            - { name: form.type, alias: ezplatform_content_forms_url_list }

    Ibexa\AdminUi\Form\Type\URLWildcard\URLWildcardDeleteType: ~

    Ibexa\AdminUi\Form\Type\URLWildcard\URLWildcardType: ~

    Ibexa\AdminUi\Form\Type\URLWildcard\URLWildcardUpdateType: ~

    Ibexa\AdminUi\Form\Type\UniversalDiscoveryWidget\UniversalDiscoveryWidgetType: ~

    Ibexa\AdminUi\Form\Type\User\UserCollectionType: ~

    Ibexa\AdminUi\Form\Type\User\UserDeleteType: ~

    Ibexa\AdminUi\Form\Type\User\UserEditType: ~

    Ibexa\AdminUi\Form\Type\User\UserGroupCollectionType: ~

    Ibexa\AdminUi\Form\Type\User\UserType: ~

    Ibexa\AdminUi\Form\Type\UserChoiceType: ~

    Ibexa\AdminUi\Form\Type\UserGroupChoiceType: ~

    Ibexa\AdminUi\Form\Type\Version\VersionRemoveType: ~

    Ibexa\AdminUi\Form\EventListener\AddLanguageFieldBasedOnContentListener: ~

    Ibexa\AdminUi\Form\EventListener\BuildPathFromRootListener: ~

    Ibexa\AdminUi\Form\EventListener\DisableSiteRootCheckboxIfRootLocationListener: ~

    Ibexa\AdminUi\Form\EventListener\SelectionMultilingualOptionsDataListener: ~

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasAssetRelation:
        tags:
            - { name: ibexa.admin_ui.form.trash_location_option, priority: 40 }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasChildren:
        tags:
            - { name: ibexa.admin_ui.form.trash_location_option, priority: 80 }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasReverseRelations:
        tags:
            - { name: ibexa.admin_ui.form.trash_location_option, priority: 100 }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasUniqueAssetRelation:
        tags:
            - { name: ibexa.admin_ui.form.trash_location_option, priority: 60 }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\OptionsFactory:
        arguments: [!tagged ibexa.admin_ui.form.trash_location_option]

    Ibexa\AdminUi\Form\Extension\RichTextTypeExtension:
        public: true
        tags:
              - { name: form.type_extension }

    Ibexa\AdminUi\Form\Extension\HelpMultilineMessageExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Ibexa\AdminUi\Form\ActionDispatcher\ContentTypeDispatcher: ~

    Ibexa\AdminUi\Form\ActionDispatcher\CreateContentOnTheFlyDispatcher: ~

    Ibexa\AdminUi\Form\ActionDispatcher\CreateUserOnTheFlyDispatcher: ~

    Ibexa\AdminUi\Form\ActionDispatcher\EditContentOnTheFlyDispatcher: ~

    Ibexa\AdminUi\Form\ActionDispatcher\EditUserOnTheFlyDispatcher: ~

    Ibexa\AdminUi\Form\Data\FormMapper\ContentTypeDraftMapper: ~

    Ibexa\AdminUi\Form\Type\ContentType\FieldDefinitionsCollectionType:
        tags:
            - { name: form.type }
