parameters:
    ezplatform.content_forms.form_processor.content_type.options.redirect_route_after_publish: ~
    ezplatform.content_forms.form_processor.content_type.options:
        redirectRouteAfterPublish: "%ezplatform.content_forms.form_processor.content_type.options.redirect_route_after_publish%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Form\Processor\:
        resource: "../../../lib/Form/Processor/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\Form\Processor\Content\AutosaveProcessor: ~

    Ibexa\AdminUi\Form\Processor\Content\ContentOnTheFlyProcessor:
        arguments:
            $innerContentFormProcessor: '@Ibexa\ContentForms\Form\Processor\ContentFormProcessor'

    Ibexa\AdminUi\Form\Processor\Content\UrlRedirectProcessor:
        public: true
        decorates: Ibexa\ContentForms\Form\Processor\SystemUrlRedirectProcessor
        arguments:
            $siteaccessGroups: '%ezpublish.siteaccess.groups%'
            $systemUrlRedirectProcessor: '@Ibexa\AdminUi\Form\Processor\Content\UrlRedirectProcessor.inner'

    Ibexa\AdminUi\Form\Processor\ContentEditNotificationFormProcessor:
        public: true
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'

    Ibexa\AdminUi\Form\Processor\ContentType\ContentTypeDiscardChangesFormProcessor: ~

    Ibexa\AdminUi\Form\Processor\ContentType\ContentTypeFormProcessor:
        arguments:
            - '@ibexa.api.service.content_type'
            - "@router"
            - "%ezplatform.content_forms.form_processor.content_type.options%"
        calls:
            - [ setGroupsList, [ '@Ibexa\Core\Helper\FieldsGroups\ArrayTranslatorFieldsGroupsList' ] ]

    Ibexa\AdminUi\Form\Processor\PreviewFormProcessor: ~

    Ibexa\AdminUi\Form\Processor\TranslationFormProcessor: ~

    Ibexa\AdminUi\Form\Processor\User\UserOnTheFlyProcessor:
        arguments:
            $innerUserUpdateFormProcessor: '@Ibexa\ContentForms\Form\Processor\User\UserUpdateFormProcessor'
