services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Ibexa\AdminUi\Form\TrashLocationOptionProvider\TrashLocationOptionProvider:
            tags: ['ezplatform.form.trash_location_option']

    Ibexa\AdminUi\Form\SubmitHandler: ~

    Ibexa\AdminUi\Form\Factory\:
        resource: '../../../lib/Form/Factory'

    Ibexa\AdminUi\Form\DataMapper\:
        resource: '../../../lib/Form/DataMapper'

    Ibexa\AdminUi\Form\Type\:
        resource: '../../../lib/Form/Type'

    Ibexa\AdminUi\Form\EventListener\:
        resource: '../../../lib/Form/EventListener'

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\:
        resource: '../../../lib/Form/TrashLocationOptionProvider'

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\OptionsFactory:
        arguments: [!tagged ezplatform.form.trash_location_option]

    Ibexa\AdminUi\Form\Type\Extension\Content\ContentEditTypeExtension:
        tags:
            - { name: form.type_extension }

    Ibexa\AdminUi\Form\Type\Policy\PolicyChoiceType:
        arguments:
            $policyMap: "%ezpublish.api.role.policy_map%"

    Ibexa\AdminUi\Form\Type\Content\Draft\ContentCreateType:
        arguments:
            $contentTypeChoiceLoader: '@Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader'
            $languageChoiceLoader: '@Ibexa\AdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader'

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader: ~

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\LanguageChoiceLoader:
        arguments:
            $configResolver: "@ezpublish.config.resolver"

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\ConfiguredLanguagesChoiceLoader:
        arguments:
            $configResolver: "@ezpublish.config.resolver"

    Ibexa\AdminUi\Form\Type\ChoiceList\Loader\TimePeriodChoiceLoader: ~

    Ibexa\AdminUi\Form\Extension\RichTextTypeExtension:
        public: true
        tags:
            - { name: form.type_extension }

    Ibexa\AdminUi\Form\Type\Role\LimitationType:
        arguments: ["@ezplatform.content_forms.limitation_form_mapper.registry", "@ezplatform.content_forms.limitation.form_mapper.null"]
        tags:
            - { name: form.type, alias: ezplatform_content_forms_policy_limitation_edit }

    Ibexa\AdminUi\Form\Type\SwitcherType: ~

    Ibexa\AdminUi\Form\Type\LocationType: ~

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeCreateType:
        arguments: ["@ezpublish.api.service.content_type"]
        tags:
            - {name: form.type, alias: ezplatform_content_forms_contenttype_create}

    Ibexa\AdminUi\Form\Type\ContentType\ContentTypeUpdateType:
        tags:
            - {name: form.type, alias: ezplatform_content_forms_contenttype_update}

    Ibexa\AdminUi\Form\Type\ContentType\FieldTypeChoiceType:
        arguments: ['@eZ\Publish\Core\FieldType\FieldTypeRegistry', '@translator']
        tags:
            - { name: form.type, alias: ezplatform_content_forms_contenttype_field_type_choice }

    Ibexa\AdminUi\Form\Type\ContentType\SortFieldChoiceType:
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: ezplatform_content_forms_contenttype_sort_field_choice }

    Ibexa\AdminUi\Form\Type\ContentType\SortOrderChoiceType:
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: ezplatform_content_forms_contenttype_sort_order_choice }

    Ibexa\AdminUi\Form\Type\FieldDefinition\FieldDefinitionType:
        arguments:
            $fieldTypeService: "@ezpublish.api.service.field_type"
            $thumbnailStrategy: '@eZ\Publish\Core\Repository\Strategy\ContentThumbnail\Field\ContentFieldStrategy'
        calls:
            - [setGroupsList, ["@ezpublish.fields_groups.list"]]
        tags:
            - { name: form.type, alias: ezplatform_content_forms_fielddefinition_update }

    Ibexa\AdminUi\Form\Type\URL\URLListType:
        arguments:
            - '@translator'
        tags:
            - { name: form.type, alias: ezplatform_content_forms_url_list }

    Ibexa\AdminUi\Form\Type\URL\URLEditType:
        tags:
            - { name: form.type, alias: ezplatform_content_forms_url_edit }

    Ibexa\AdminUi\Form\Extension\HelpMultilineMessageExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasReverseRelations:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 100 }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasChildren:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 80 }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasUniqueAssetRelation:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 60 }

    Ibexa\AdminUi\Form\TrashLocationOptionProvider\HasAssetRelation:
        tags:
            - { name: 'ezplatform.form.trash_location_option', priority: 40 }

    Ibexa\AdminUi\Form\Type\Search\SearchType:
        arguments:
            $baseType: '@Ibexa\Platform\Bundle\Search\Form\Type\SearchType'
            $translator: '@translator'
        tags:
            - { name: form.type, alias: Ibexa\AdminUi\Form\Type\Search\SearchType }
