services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\AdminUi\Notifier\PasswordReset:
        decorates: Ibexa\Contracts\User\PasswordReset\NotifierInterface
        arguments:
            $projectDir: '%kernel.project_dir%'

    Ibexa\AdminUi\Notifier\UserInvitation:
        decorates: Ibexa\Contracts\User\Invitation\InvitationSender
        arguments:
            $projectDir: '%kernel.project_dir%'
