services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\AdminUi\Form\Processor\Content\ContentOnTheFlyProcessor:
        arguments:
            $innerContentFormProcessor: '@ezplatform.content_forms.form_processor.content'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\AdminUi\Form\Processor\User\UserOnTheFlyProcessor:
        arguments:
            $innerUserUpdateFormProcessor: '@ezplatform.content_forms.form_processor.user_update'
        tags:
            - { name: kernel.event_subscriber }
