services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Permission\PermissionChecker: ~

    Ibexa\Contracts\AdminUi\Permission\PermissionCheckerInterface:
        alias: Ibexa\AdminUi\Permission\PermissionChecker

    Ibexa\AdminUi\Permission\LookupLimitationsTransformer: ~
