services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\QueryType\LocationPathQueryType: ~

    Ibexa\AdminUi\QueryType\ContentSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\MediaSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\TrashSearchQueryType: ~
