services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\QueryType\LocationPathQueryType: ~

    Ibexa\AdminUi\QueryType\ContentSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\MediaSubtreeQueryType: ~

    Ibexa\AdminUi\QueryType\SearchQueryType:
        deprecated: 'Service "%service_id%" is deprecated since 3.1 and will be removed in 3.2. Use "Ibexa\Platform\Search\QueryType\SearchQueryType" instead'
        arguments:
            $searchService: '@ezpublish.api.service.search'

    Ibexa\AdminUi\QueryType\TrashSearchQueryType: ~
