services:
  Ibexa\AdminUi\Search\AbstractPagerContentToDataMapper:
    abstract: true
    autowire: true
    public: false
    arguments:
      $translationHelper: '@ezpublish.translation_helper'

  Ibexa\AdminUi\Search\PagerSearchContentToDataMapper:
    parent: Ibexa\Platform\Search\Mapper\PagerSearchContentToDataMapper
    autowire: true
    public: false
