services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Service\MetaFieldType\MetaFieldDefinitionService: ~

    Ibexa\AdminUi\Service\MetaFieldType\MetaFieldDefinitionServiceInterface:
        '@Ibexa\AdminUi\Service\MetaFieldType\MetaFieldDefinitionService'

    Ibexa\AdminUi\Service\ContentTypeFieldsByExpressionService: ~

    Ibexa\Contracts\AdminUi\Service\ContentTypeFieldsByExpressionServiceInterface:
        '@Ibexa\AdminUi\Service\ContentTypeFieldsByExpressionService'