services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Service\MetaFieldType\MetaFieldDefinitionService: ~

    Ibexa\AdminUi\Service\MetaFieldType\MetaFieldDefinitionServiceInterface:
        '@Ibexa\AdminUi\Service\MetaFieldType\MetaFieldDefinitionService'
