services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\AdminUi\Validator\Constraints\:
        resource: "../../../lib/Validator/Constraints"

    Ibexa\AdminUi\Validator\Constraints\UserPasswordValidator:
        tags:
            - { name: validator.constraint_validator }

    Ibexa\AdminUi\Validator\Constraints\LocationIsWithinCopySubtreeLimitValidator:
        arguments:
            $configResolver: '@ezpublish.config.resolver'

    Ibexa\AdminUi\Validator\Constraints\UniqueContentTypeIdentifierValidator:
        arguments: ["@ezpublish.api.service.content_type"]
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.unique_content_type_identifier }

    ezplatform.content_forms.validator.field_type.abstract:
        class: Ibexa\AdminUi\Validator\Constraints\FieldTypeValidator
        arguments: ["@ezpublish.api.service.field_type"]
        abstract: true
        autoconfigure: false

    Ibexa\AdminUi\Validator\Constraints\ValidatorConfigurationValidator:
        parent: ezplatform.content_forms.validator.field_type.abstract
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.validator_configuration }

    Ibexa\AdminUi\Validator\Constraints\FieldSettingsValidator:
        parent: ezplatform.content_forms.validator.field_type.abstract
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.field_settings }

    Ibexa\AdminUi\Validator\Constraints\UniqueURLValidator:
        arguments:
            - '@ezpublish.api.service.url'
        tags:
            - { name: validator.constraint_validator, alias: ezplatform.content_forms.validator.unique_url }

