services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Bundle\AdminUi\ValueResolver\:
        resource: "../../ValueResolver/*"
        tags:
            -   name: controller.argument_value_resolver
                priority: 150

    Ibexa\Bundle\AdminUi\ValueResolver\UniversalDiscoveryRequestQueryValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    Ibexa\Bundle\AdminUi\ValueResolver\ContentTreeChildrenQueryValueResolver:
        arguments:
            $criterionProcessor: '@Ibexa\AdminUi\REST\Input\Parser\CriterionProcessor'
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
